"""
Build a comparison table (Cosine baseline vs Seq2Seq) for paper reporting.
"""
import os
import csv
import json
import argparse


def main():
    parser = argparse.ArgumentParser(description="Create comparison table CSV for paper.")
    parser.add_argument("--seq2seq-metrics", required=True,
                        help="Path to seq2seq_eval_metrics.json generated by research_eval_seq2seq.py")
    parser.add_argument("--output-csv", default="research_outputs/comparison_table.csv",
                        help="Output CSV path")
    parser.add_argument("--cosine-top1", type=float, default=30.7)
    parser.add_argument("--cosine-top3", type=float, default=45.0)
    parser.add_argument("--cosine-top5", type=float, default=49.4)
    parser.add_argument("--cosine-inference-ms", type=float, default=3.0)
    args = parser.parse_args()

    with open(args.seq2seq_metrics, "r", encoding="utf-8") as f:
        m = json.load(f)

    seq_top1 = float(m.get("top1_accuracy", 0.0))
    seq_top3 = float(m.get("top3_accuracy", 0.0))
    seq_top5 = float(m.get("top5_accuracy", 0.0))
    seq_total_ms = float(m.get("latency_sec", {}).get("total_mean", 0.0)) * 1000.0
    seq_decode_ms = float(m.get("latency_sec", {}).get("decode_mean", 0.0)) * 1000.0
    seq_feature_ms = float(m.get("latency_sec", {}).get("feature_mean", 0.0)) * 1000.0

    os.makedirs(os.path.dirname(args.output_csv) or ".", exist_ok=True)
    with open(args.output_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["model", "top1_acc_percent", "top3_acc_percent", "top5_acc_percent",
                         "inference_ms", "feature_ms", "total_ms"])
        writer.writerow(["cosine_retrieval", args.cosine_top1, args.cosine_top3, args.cosine_top5,
                         args.cosine_inference_ms, "", ""])
        writer.writerow(["seq2seq_attention", seq_top1, seq_top3, seq_top5,
                         seq_decode_ms, seq_feature_ms, seq_total_ms])

    print(f"Saved comparison table: {args.output_csv}")


if __name__ == "__main__":
    main()
